%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1920
image_height: 1200
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 7.29468089e+02
   fy: 7.29468089e+02
   cx: 9.23479507e+02
   cy: 6.11102386e+02
