%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1920
image_height: 1200
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 729.4680885
   fy: 729.4680885
   cx: 923.47950745
   cy: 611.10238647
